version: 2
project_name: kubectl-pod_instance_types

builds:
  - id: kubectl-pod_instance_types
    main: ./cmd/kubectl-pod_instance_types
    binary: kubectl-pod_instance_types
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags: [-s -w]
    env: [CGO_ENABLED=0]
    ignore: [{ goos: windows, goarch: arm64 }]

archives:
  - ids: [kubectl-pod_instance_types]
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: false
    format_overrides: [formats: [tar.gz]]
    files: [LICENSE]
